### PR TITLE
Updating Turnpike (Web, Nginx, & Prometheus) Dockerfiles to use UBI8-Minimal

### PR DESCRIPTION
**Pull request by casey-williams-rh**
Jira Ticket: https://issues.redhat.com/browse/RHCLOUD-11345

### Overview:
Adding updates to Turnpike (Web, Nginx, & Prometheus) Dockerfiles to use `ubi8-minimal`. Additionally, a new Dockerfile has been created to continue support of local dev testing.

### Changes:
- The `./Dockerfile`, `./nginx/Dockerfile`, and `./nginx/Dockerfile-prometheus` are now using `ubi8-minimal` as their base image. This is so that the `ubi8-minimal` base image will be used on deployments to production environments rather than `centos/stream8`, offering a smaller footprint and security benefits.

- Within `./Dockerfile` we now enable RH "**CodeReady Builder**" to provide the same libraries and developer tools to the UBI image as "**Powertools**" does for CentOS.

- `./Dockerfile-env` has been created to deploy turnpike web locally using the `centos/stream8` base image. This provides ease of use for local dev testing, especially when paired with the updated docker-compose file.

- `./docker-compose.yml` has been updated to use `./Dockerfile-env`, again, to provide and maintain ease of use for local dev testing.

### Testing:
- Conducted local dev testing using the newly updated `./docker-compose.yml` (using updated dockerfiles). 
   - All local tests **passed**. 

- The updated `./Dockerfile` using `ubi8-minimal` was built within an RHEL8 VM with no build errors. Further testing will be conducted upon deployment to our ephemeral environments. 

- The updated `./nginx/Dockerfile` and `./nginx/Dockerfile-prometheus` using `ubi8-minimal` were built locally (outside of RHEL8) with no build errors.

### CODE REVIEW

**Review by astrozzc — COMMENTED** [review]
LGTM, maybe I missed this, curious why we are keeping a different dockerfile-env for docker-compose? Could they just use the Dockerfile?

**Comment by casey-williams-rh** [comment]
@astrozzc , We are using the "Dockerfile-env" files within the Docker-Compose file to build the local dev environment using CentOS. Using the newly updated standard Dockerfiles will attempt to build out the local dev environment using UBI8. The local build will fail because we can not enable "CodeReady Builder" due to not being on an RHEL system with an active subscription.

```
[turnpike_web 6/8] RUN dnf config-manager --set-enable codeready-builder-for-rhel-8-x86_64-rpms:
#12 0.535 Error: No matching repo to modify: codeready-builder-for-rhel-8-x86_64-rpms. 
```

"CodeReady Builder" is needed to enable the download of "-devel" RPMs needed for turnpike-web's execution. However, we can enable the "Powertools" repo in CentOS, which we have used in the past, and "Powertools" is the CentOS equivalent to "CodeReady Builder" in RHEL.

With all that being said, there is a chance we can build turnpike-nginx and prometheus with UBI8 locally and the build be successful. As they don't require the "Powertools" or "CodeReady Builder" repos. If that is the case, we can remove the "-env" Dockerfiles for them.

I'll do some testing and see what I can cook up.

**Comment by astrozzc** [comment]
> @astrozzc , We are using the "Dockerfile-env" files within the Docker-Compose file to build the local dev environment using CentOS. Using the newly updated standard Dockerfiles will attempt to build out the local dev environment using UBI8. The local build will fail because we can not enable "CodeReady Builder" due to not being on an RHEL system with an active subscription.
> 
> ```
> [turnpike_web 6/8] RUN dnf config-manager --set-enable codeready-builder-for-rhel-8-x86_64-rpms:
> #12 0.535 Error: No matching repo to modify: codeready-builder-for-rhel-8-x86_64-rpms. 
> ```
> 
> "CodeReady Builder" is needed to enable the download of "-devel" RPMs needed for turnpike-web's execution. However, we can enable the "Powertools" repo in CentOS, which we have used in the past, and "Powertools" is the CentOS equivalent to "CodeReady Builder" in RHEL.
> 
> With all that being said, there is a chance we can build turnpike-nginx and prometheus with UBI8 locally and the build be successful. As they don't require the "Powertools" or "CodeReady Builder" repos. If that is the case, we can remove the "-env" Dockerfiles for them.
> 
> I'll do some testing and see what I can cook up.

Got it, thanks for the info 👍

**Review by astrozzc — APPROVED** [review]
LGTM

**Review by wcmitchell — APPROVED** [review]
👍

**Pull request merged**
